### ISSUE TITLE
InternalServerErrorException(status_code=500, message='Internal Server Error')

### ISSUE THREAD

**Issue by homanmirgolbabaee** [toolhouse-community/sample-flask#1]
I've created .env , replaced my api keys from anthropic and toolhouse.
i've installed the following tools on toolstore :

1. Get page contents - Scraper
2. Web search - Web search

but i get internal server error , can you help me out ?

![issue-th](https://github.com/user-attachments/assets/d9fdb809-60dd-4978-b769-ecb679e4ee30)
![Screenshot 2024-06-27 152413](https://github.com/user-attachments/assets/2bf176cd-afe3-43dd-9199-25f77ad33dd9)

**Comment by aaishikasb** [comment]
Thanks for pointing this out @homanmirgolbabaee! A fix is underway!
